### ISSUE TITLE
Correct usage with extract-text-webpack-plugin?

### ISSUE THREAD

**Issue by dylanpyle** [akim-mcmath/ejs-html-loader#1]
I'm investigating using this in combination with `extract-text-webpack-plugin` to turn a large number of EJS files directly into HTML files without producing JavaScript bundles along the way. I've got a solution working, but it doesn't feel ideal — I'd love your input on a better approach. Here's the relevant pieces of my webpack config:

``` javascript
const glob = require('glob');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const ejsExtract = new ExtractTextPlugin(2, '[name]');

const entries = {};

glob.sync('./ejs/*.ejs').forEach((path) => {
  const fileName = path.match(/(\w+).ejs/)[1];
  entries[fileName + '.html'] = path;
});

const webpackConfig = {
  entry: entries,

  output: {
    path: __dirname + '/dist',
    filename: '[name]' // will be initialized as a JS file, but overwritten by ExtractTextPlugin afterwards
  },

  module: {
    loaders: [
      {
        test: /\.ejs$/,
        loader: ejsExtract.extract(['raw', 'ejs-html'])
      }
    ]
  },

  plugins: [
    ejsExtract
  ],

  resolve: {
    extensions: ['', '.js', '.scss', '.ejs']
  },

  ejsHtml: {
    some_data: 'goes here'
  }
};
```

(yes, this is a bit crazy, feel free to close if you don't want to go down this rabbit hole)

**Comment by dylanpyle** [comment]
The more research I'm doing into extract-text-webpack-plugin, the more I'm thinking this is the closest I'm going to get to a "decent" solution. Sorry for the noise!

**Comment by akim-mcmath** [comment]
Sorry for failing to reply earlier. I know this is closed, but I might take a look at it later and see if I can be of any help. I'm just a bit preoccupied right now.

**Comment by mcmath** [comment]
I think your intuition is right that you are unlikely to find a very elegant solution to your problem. Webpack,  at its core, is intended to combine all your static assets into one or a few JavaScript bundles. You can, of course, deviate from that core function using plugins and loaders. But the more you deviate, the more convoluted your solution is likely to become. Since you want to produce a lot of files without any JavaScript bundles, you can expect an inelegant and somewhat hacky configuration file.

That said, if you can handle just one JavaScript bundle – and it would be unusual not to have one if using Webpack – you might do better to forgo the `extract-text-plugin`, `raw-loader`, and `glob` module, and to use the [`file-loader`](https://github.com/webpack/file-loader) along with a [`require.context`](https://webpack.github.io/docs/context.html) instead. Your Webpack configuration file will include something like this:

``` js
entry: 'src/entry.js',
output: {
  path: `${__dirname}/dist`,
  filename: '[name].bundle.js'
},
module: {
  loaders: [
    {
      test: /\.ejs$/,
      loader: 'file?name=[name].html!ejs-html'
    }
  ]
},
ejsHtml: {
  // ...
}
```

The above configuration will produce a `.html` in your output directory for every `.ejs` file you `require()`. However, if you have a large number of such files, you don't want to `require()` all of them; instead, in `entry.js`, you can use a `require.context`, like so:

``` js
var req = require.context('.', true, /\.ejs$/);
req.keys().map(req);
```

This will effectively `require()` all `.ejs` files in the `src` directory and any subdirectories. You will, of course, be left with an `entry.bundle.js` file. If you are hoping to avoid that, then some inelegant hack will still be needed. But if you don't want even one JavaScript bundle in your output, then you might want to reconsider whether Webpack is the right tool to begin with.
