### ISSUE TITLE
how to send message to include ejs file?

### ISSUE THREAD

**Issue by Iamlars** [akim-mcmath/ejs-html-loader#7]
like  `<%-include("_header.html",{active: 'index'})%>`, I  want to send `{active: 'index'}` to `_header.html`. but it is not work well.

**Comment by mcmath** [comment]
This loader is not compatible with dynamic includes, at least when watch mode is enabled. You have to use the following syntax:

```ejs
<% include _header.html %>
```

Here, `_header.html` inherits the locals available in the including file. So you should pass the `active` property directly as an option to the loader.

```js
{
  test: /\.ejs$/
  loader: 'ejs-html-loader'
  options: {
    // ...
    active: 'index'
    // ...
  }
}
```

In more complicated cases, such as when you want to include a partial several times with different data, you can do something like this:

```ejs
<% for (const { name, species } of pets) { %>
  <% include _pet.ejs %>
<% } %>
```

Where `_pet.ejs` might look like this:

```ejs
<div class="pet">
  <h2><%- name %></h2>
  <p><%- species %></p>
</div>
```

And you would pass something like the following as an option:

```js
{
  // ...
  pets: [
    { name: "Max", species: "cat" },
    { name: "Gromit", species: "dog" }
  ]
  // ...
}
```

The reason this syntax is required is because the loader statically analyzes the included files so it can keep track of them in watch mode. Static analysis is not possible with dynamic includes.

I'm working on an update to this loader at the moment, however. I'll consider whether there is some way of keeping track of dynamic includes, since it would be a nice feature.
